spring:
  application:
    name: loan-platform-backend
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/loan_platform}
    username: ${DB_USERNAME:loan_platform}
    password: ${DB_PASSWORD:loan_platform}
  jooq:
    sql-dialect: postgres
  flyway:
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
